### ISSUE TITLE
Error I receieved

### ISSUE THREAD

**Issue by ameet-rao** [slxmmy999/ChatGPT-Mobile#15]
Traceback (most recent call last):
  File "src/gmail_server.py", line 7, in <module>
    import sms_api
  File "/Users/ameet9034/ChatGPT-Mobile/src/sms_api.py", line 2, in <module>
    from log import AppLogger
  File "/Users/ameet9034/ChatGPT-Mobile/src/log.py", line 19
    match type.lower():
          ^
SyntaxError: invalid syntax

**Comment by slxmmy999** [comment]
I believe this is most likely an issue with the version of Python you are using. Support for `match/case` statements was added somewhat recently in Python version 3.10 so you must be using this version or higher. Please let me know if this solves your issue and I will make a note to add this to the README.

**Comment by admirerr** [comment]
@slxmmy999 I am also facing similar issue though I am using Python 3.9.12

<img width="735" alt="image" src="https://github.com/slxmmy999/ChatGPT-Mobile/assets/79766263/9ee24455-49c6-4c0e-9582-0fd3752f78c2">

**Comment by admirerr** [comment]
> @slxmmy999 I am also facing similar issue though I am using Python 3.9.12
> 
> <img alt="image" width="735" src="https://user-images.githubusercontent.com/79766263/264253392-9ee24455-49c6-4c0e-9582-0fd3752f78c2.png">

I upgraded version of Python to 3.11 and now it's working fine.
